### ISSUE TITLE
添加一个网站

### ISSUE THREAD

**Issue by SakurajimaMaii** [teedoc/teedoc.github.io#99]
网站：VastUtils官网(https://sakurajimamaii.github.io/VastDocs/)
简介：一款加快你安卓开发的安卓工具集     Easy Quick Android Utils for you to faster project development
源码：https://github.com/SakurajimaMaii/VastUtils

**Comment by Neutree** [comment]
:ok_hand:  添加好了 https://teedoc.github.io/get_started/zh/usage/sites.html
